# -*- coding: utf-8 -*-
"""crop_images.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15kfJZqRMIC2p89E-2FXVOnt5MR-1dXty
"""

import cv2

def crop_image(img):
  images = []
  imageWidth = img.shape[0]
  imageHeight = img.shape[1] 
  gridx=256
  gridy=256
  rangex=imageWidth/gridx
  rangey=imageHeight/gridy
  images = []
  for x in range(int(rangex)):
    for y in range(int(rangey)):
      crop_img = img[y*gridy:y*gridy + gridy, x*gridx:x*gridx + gridx]
      if(crop_img.shape == (256,256,3)):
        images.append(crop_img)

  return images